<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Opportunity;
use App\Models\OpportunityCategory;

class OpportunitySeeder extends Seeder
{
    public function run(): void
    {
        $opportunities = [

            // BANKING
            ['category' => 'banking', 'name' => 'IBPS PO 2025', 'hindi_name' => 'आईबीपीएस पीओ 2025',
             'slug' => 'ibps-po-2025', 'conducting_body' => 'IBPS', 'post_name' => 'Probationary Officer',
             'level' => 'central', 'description' => 'IBPS PO recruitment for Probationary Officers in public sector banks across India.',
             'eligibility_rules_json' => ['min_age' => 20, 'max_age' => 30, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'Graduation Certificate', 'Photo'],
             'vacancy_count' => 4455, 'salary_range' => '₹36,000 – ₹63,840/month',
             'apply_url' => 'https://ibps.in', 'official_site' => 'https://ibps.in',
             'apply_end' => '2025-08-15', 'is_featured' => true],

            ['category' => 'banking', 'name' => 'SBI PO 2025', 'hindi_name' => 'एसबीआई पीओ 2025',
             'slug' => 'sbi-po-2025', 'conducting_body' => 'SBI', 'post_name' => 'Probationary Officer',
             'level' => 'central', 'description' => 'State Bank of India recruitment for Probationary Officers.',
             'eligibility_rules_json' => ['min_age' => 21, 'max_age' => 30, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'Graduation Certificate', 'Photo'],
             'vacancy_count' => 2000, 'salary_range' => '₹41,960 – ₹63,840/month',
             'apply_url' => 'https://sbi.co.in/careers', 'official_site' => 'https://sbi.co.in',
             'apply_end' => '2025-09-10', 'is_featured' => true],

            ['category' => 'banking', 'name' => 'IBPS Clerk 2025', 'hindi_name' => 'आईबीपीएस क्लर्क 2025',
             'slug' => 'ibps-clerk-2025', 'conducting_body' => 'IBPS', 'post_name' => 'Clerk',
             'level' => 'central', 'description' => 'IBPS Clerk recruitment for clerical posts in public sector banks.',
             'eligibility_rules_json' => ['min_age' => 20, 'max_age' => 28, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'Graduation Certificate', 'Photo'],
             'vacancy_count' => 6128, 'salary_range' => '₹26,000 – ₹29,000/month',
             'apply_url' => 'https://ibps.in', 'official_site' => 'https://ibps.in',
             'apply_end' => '2025-09-20'],

            ['category' => 'banking', 'name' => 'RBI Grade B 2025', 'hindi_name' => 'आरबीआई ग्रेड बी 2025',
             'slug' => 'rbi-grade-b-2025', 'conducting_body' => 'RBI', 'post_name' => 'Officer Grade B',
             'level' => 'central', 'description' => 'Reserve Bank of India Grade B Officer recruitment.',
             'eligibility_rules_json' => ['min_age' => 21, 'max_age' => 30, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'Graduation Certificate', 'Photo'],
             'vacancy_count' => 291, 'salary_range' => '₹55,000 – ₹1,10,000/month',
             'apply_url' => 'https://rbi.org.in', 'official_site' => 'https://rbi.org.in',
             'apply_end' => '2025-10-01', 'is_featured' => true],

            ['category' => 'banking', 'name' => 'LIC AAO 2025', 'hindi_name' => 'एलआईसी एएओ 2025',
             'slug' => 'lic-aao-2025', 'conducting_body' => 'LIC', 'post_name' => 'Assistant Administrative Officer',
             'level' => 'central', 'description' => 'LIC recruitment for AAO posts across India.',
             'eligibility_rules_json' => ['min_age' => 21, 'max_age' => 30, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'Graduation Certificate', 'Photo'],
             'vacancy_count' => 300, 'salary_range' => '₹53,600 – ₹86,700/month',
             'apply_url' => 'https://licindia.in', 'official_site' => 'https://licindia.in',
             'apply_end' => '2025-11-15'],

            // RAILWAY
            ['category' => 'railway', 'name' => 'RRB NTPC 2025', 'hindi_name' => 'आरआरबी एनटीपीसी 2025',
             'slug' => 'rrb-ntpc-2025', 'conducting_body' => 'Railway Recruitment Board', 'post_name' => 'Non-Technical Popular Categories',
             'level' => 'central', 'description' => 'RRB NTPC recruitment for various non-technical posts in Indian Railways.',
             'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 33, 'min_education' => '12th'],
             'documents_required_json' => ['Aadhaar', '10th Certificate', '12th Certificate', 'Photo'],
             'vacancy_count' => 11558, 'salary_range' => '₹19,900 – ₹35,400/month',
             'apply_url' => 'https://indianrailways.gov.in', 'official_site' => 'https://rrbcdg.gov.in',
             'apply_end' => '2025-08-30', 'is_featured' => true],

            ['category' => 'railway', 'name' => 'RRB Group D 2025', 'hindi_name' => 'आरआरबी ग्रुप डी 2025',
             'slug' => 'rrb-group-d-2025', 'conducting_body' => 'Railway Recruitment Board', 'post_name' => 'Group D Level 1',
             'level' => 'central', 'description' => 'RRB Group D recruitment for Track Maintainer, Helper and other posts.',
             'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 33, 'min_education' => '10th'],
             'documents_required_json' => ['Aadhaar', '10th Certificate', 'Photo'],
             'vacancy_count' => 103769, 'salary_range' => '₹18,000 – ₹25,000/month',
             'apply_url' => 'https://indianrailways.gov.in', 'official_site' => 'https://rrbcdg.gov.in',
             'apply_end' => '2025-09-25'],

            ['category' => 'railway', 'name' => 'RPF Constable 2025', 'hindi_name' => 'आरपीएफ कांस्टेबल 2025',
             'slug' => 'rpf-constable-2025', 'conducting_body' => 'Railway Protection Force', 'post_name' => 'Constable',
             'level' => 'central', 'description' => 'RPF Constable recruitment to protect railway property and passengers.',
             'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 28, 'min_education' => '10th'],
             'documents_required_json' => ['Aadhaar', '10th Certificate', 'Photo'],
             'vacancy_count' => 4660, 'salary_range' => '₹21,700 – ₹69,100/month',
             'apply_url' => 'https://indianrailways.gov.in', 'official_site' => 'https://rpf.indianrailways.gov.in',
             'apply_end' => '2025-10-15'],

            // SSC
            ['category' => 'ssc', 'name' => 'SSC CGL 2025', 'hindi_name' => 'एसएससी सीजीएल 2025',
             'slug' => 'ssc-cgl-2025', 'conducting_body' => 'Staff Selection Commission', 'post_name' => 'Combined Graduate Level',
             'level' => 'central', 'description' => 'SSC CGL for various Group B and C posts in central government departments.',
             'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 32, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'Graduation Certificate', 'Photo'],
             'vacancy_count' => 17727, 'salary_range' => '₹25,500 – ₹1,51,100/month',
             'apply_url' => 'https://ssc.gov.in', 'official_site' => 'https://ssc.gov.in',
             'apply_end' => '2025-08-20', 'is_featured' => true],

            ['category' => 'ssc', 'name' => 'SSC CHSL 2025', 'hindi_name' => 'एसएससी सीएचएसएल 2025',
             'slug' => 'ssc-chsl-2025', 'conducting_body' => 'Staff Selection Commission', 'post_name' => 'Combined Higher Secondary Level',
             'level' => 'central', 'description' => 'SSC CHSL for LDC, JSA, PA, SA and DEO posts.',
             'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 27, 'min_education' => '12th'],
             'documents_required_json' => ['Aadhaar', '12th Certificate', 'Photo'],
             'vacancy_count' => 3712, 'salary_range' => '₹19,900 – ₹63,200/month',
             'apply_url' => 'https://ssc.gov.in', 'official_site' => 'https://ssc.gov.in',
             'apply_end' => '2025-09-05'],

            ['category' => 'ssc', 'name' => 'SSC GD Constable 2025', 'hindi_name' => 'एसएससी जीडी 2025',
             'slug' => 'ssc-gd-2025', 'conducting_body' => 'Staff Selection Commission', 'post_name' => 'General Duty Constable',
             'level' => 'central', 'description' => 'SSC GD Constable recruitment for CAPF, NIA, SSF and Rifleman.',
             'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 23, 'min_education' => '10th'],
             'documents_required_json' => ['Aadhaar', '10th Certificate', 'Photo'],
             'vacancy_count' => 39481, 'salary_range' => '₹21,700 – ₹69,100/month',
             'apply_url' => 'https://ssc.gov.in', 'official_site' => 'https://ssc.gov.in',
             'apply_end' => '2025-10-20', 'is_featured' => true],

            ['category' => 'ssc', 'name' => 'SSC MTS 2025', 'hindi_name' => 'एसएससी एमटीएस 2025',
             'slug' => 'ssc-mts-2025', 'conducting_body' => 'Staff Selection Commission', 'post_name' => 'Multi Tasking Staff',
             'level' => 'central', 'description' => 'SSC MTS for Multi Tasking Non-Technical Staff posts.',
             'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 25, 'min_education' => '10th'],
             'documents_required_json' => ['Aadhaar', '10th Certificate', 'Photo'],
             'vacancy_count' => 8326, 'salary_range' => '₹18,000 – ₹22,000/month',
             'apply_url' => 'https://ssc.gov.in', 'official_site' => 'https://ssc.gov.in',
             'apply_end' => '2025-11-01'],

            // CIVIL SERVICES
            ['category' => 'civil-services', 'name' => 'UPSC CSE 2025', 'hindi_name' => 'यूपीएससी सिविल सेवा 2025',
             'slug' => 'upsc-cse-2025', 'conducting_body' => 'UPSC', 'post_name' => 'IAS/IPS/IFS Officer',
             'level' => 'central', 'description' => 'UPSC Civil Services Examination for IAS, IPS, IFS and other Group A services.',
             'eligibility_rules_json' => ['min_age' => 21, 'max_age' => 32, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'Graduation Certificate', 'Photo', 'Caste Certificate'],
             'vacancy_count' => 1056, 'salary_range' => '₹56,100 – ₹2,50,000/month',
             'apply_url' => 'https://upsc.gov.in', 'official_site' => 'https://upsc.gov.in',
             'apply_end' => '2025-08-05', 'is_featured' => true],

            ['category' => 'civil-services', 'name' => 'BPSC 2025', 'hindi_name' => 'बीपीएससी 2025',
             'slug' => 'bpsc-2025', 'conducting_body' => 'Bihar Public Service Commission', 'post_name' => 'State Civil Service Officer',
             'level' => 'state', 'state_code' => 'BR', 'description' => 'Bihar PSC Combined Competitive Examination for various state civil service posts.',
             'eligibility_rules_json' => ['min_age' => 20, 'max_age' => 37, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'Graduation Certificate', 'Domicile Certificate', 'Photo'],
             'vacancy_count' => 346, 'salary_range' => '₹44,900 – ₹1,42,400/month',
             'apply_url' => 'https://bpsc.bih.nic.in', 'official_site' => 'https://bpsc.bih.nic.in',
             'apply_end' => '2025-09-30', 'is_featured' => true],

            // DEFENCE
            ['category' => 'defence', 'name' => 'Agniveer Army 2025', 'hindi_name' => 'अग्निवीर सेना 2025',
             'slug' => 'agniveer-army-2025', 'conducting_body' => 'Indian Army', 'post_name' => 'Agniveer',
             'level' => 'central', 'description' => 'Indian Army Agniveer recruitment under Agnipath scheme for 4 years.',
             'eligibility_rules_json' => ['min_age' => 17, 'max_age' => 23, 'min_education' => '10th'],
             'documents_required_json' => ['Aadhaar', '10th Certificate', 'Photo', 'Medical Certificate'],
             'vacancy_count' => 25000, 'salary_range' => '₹30,000 – ₹40,000/month',
             'apply_url' => 'https://joinindianarmy.nic.in', 'official_site' => 'https://joinindianarmy.nic.in',
             'apply_end' => '2025-08-25', 'is_featured' => true],

            ['category' => 'defence', 'name' => 'NDA 2025', 'hindi_name' => 'एनडीए 2025',
             'slug' => 'nda-2025', 'conducting_body' => 'UPSC', 'post_name' => 'National Defence Academy',
             'level' => 'central', 'description' => 'NDA exam for entry into Army, Navy and Air Force as officer.',
             'eligibility_rules_json' => ['min_age' => 16, 'max_age' => 19, 'min_education' => '12th', 'gender' => 'male'],
             'documents_required_json' => ['Aadhaar', '12th Certificate', 'Photo'],
             'vacancy_count' => 400, 'salary_range' => '₹56,100 – ₹2,50,000/month',
             'apply_url' => 'https://upsc.gov.in', 'official_site' => 'https://upsc.gov.in',
             'apply_end' => '2025-09-15'],

            ['category' => 'defence', 'name' => 'AFCAT 2025', 'hindi_name' => 'एएफसीएटी 2025',
             'slug' => 'afcat-2025', 'conducting_body' => 'Indian Air Force', 'post_name' => 'Flying/Ground Duty Officer',
             'level' => 'central', 'description' => 'Air Force Common Admission Test for officer entry in IAF.',
             'eligibility_rules_json' => ['min_age' => 20, 'max_age' => 26, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'Graduation Certificate', 'Photo'],
             'vacancy_count' => 304, 'salary_range' => '₹56,100 – ₹1,77,500/month',
             'apply_url' => 'https://afcat.cdac.in', 'official_site' => 'https://indianairforce.nic.in',
             'apply_end' => '2025-10-10'],

            // TEACHING
            ['category' => 'teaching', 'name' => 'CTET 2025', 'hindi_name' => 'सीटेट 2025',
             'slug' => 'ctet-2025', 'conducting_body' => 'CBSE/NTA', 'post_name' => 'Primary & Upper Primary Teacher',
             'level' => 'central', 'description' => 'Central Teacher Eligibility Test for teaching in central govt schools.',
             'eligibility_rules_json' => ['min_age' => 18, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'B.Ed Certificate', 'Graduation Certificate', 'Photo'],
             'vacancy_count' => null, 'salary_range' => '₹35,400 – ₹1,12,400/month',
             'apply_url' => 'https://ctet.nic.in', 'official_site' => 'https://ctet.nic.in',
             'apply_end' => '2025-09-20'],

            ['category' => 'teaching', 'name' => 'UGC NET 2025', 'hindi_name' => 'यूजीसी नेट 2025',
             'slug' => 'ugc-net-2025', 'conducting_body' => 'NTA', 'post_name' => 'Assistant Professor / JRF',
             'level' => 'central', 'description' => 'UGC NET for Assistant Professor and Junior Research Fellowship eligibility.',
             'eligibility_rules_json' => ['min_age' => 18, 'min_education' => 'post graduate'],
             'documents_required_json' => ['Aadhaar', 'Post Graduation Certificate', 'Photo'],
             'vacancy_count' => null, 'salary_range' => '₹57,700 – ₹1,82,400/month',
             'apply_url' => 'https://ugcnet.nta.ac.in', 'official_site' => 'https://ugcnet.nta.ac.in',
             'apply_end' => '2025-10-05'],

            // HEALTHCARE
            ['category' => 'healthcare', 'name' => 'AIIMS Staff Nurse 2025', 'hindi_name' => 'एम्स स्टाफ नर्स 2025',
             'slug' => 'aiims-nurse-2025', 'conducting_body' => 'AIIMS', 'post_name' => 'Staff Nurse Grade II',
             'level' => 'central', 'description' => 'AIIMS Staff Nurse recruitment across AIIMS hospitals India.',
             'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 30, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'B.Sc Nursing Certificate', 'Photo', 'Registration Certificate'],
             'vacancy_count' => 1372, 'salary_range' => '₹44,900 – ₹1,42,400/month',
             'apply_url' => 'https://aiimsexams.ac.in', 'official_site' => 'https://aiimsexams.ac.in',
             'apply_end' => '2025-09-10'],

            // ENGINEERING
            ['category' => 'engineering', 'name' => 'ISRO Scientist 2025', 'hindi_name' => 'इसरो वैज्ञानिक 2025',
             'slug' => 'isro-scientist-2025', 'conducting_body' => 'ISRO', 'post_name' => 'Scientist/Engineer SC',
             'level' => 'central', 'description' => 'ISRO recruitment for Scientist and Engineer posts in space research.',
             'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 35, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'B.Tech Certificate', 'Photo'],
             'vacancy_count' => 303, 'salary_range' => '₹56,100 – ₹1,77,500/month',
             'apply_url' => 'https://isro.gov.in', 'official_site' => 'https://isro.gov.in',
             'apply_end' => '2025-10-20', 'is_featured' => true],

            ['category' => 'engineering', 'name' => 'DRDO Scientist B 2025', 'hindi_name' => 'डीआरडीओ वैज्ञानिक बी 2025',
             'slug' => 'drdo-scientist-2025', 'conducting_body' => 'DRDO', 'post_name' => 'Scientist B',
             'level' => 'central', 'description' => 'DRDO Scientist B recruitment for defence research and development.',
             'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 28, 'min_education' => 'graduate'],
             'documents_required_json' => ['Aadhaar', 'B.Tech Certificate', 'Photo'],
             'vacancy_count' => 185, 'salary_range' => '₹56,100 – ₹1,77,500/month',
             'apply_url' => 'https://rac.gov.in', 'official_site' => 'https://drdo.gov.in',
             'apply_end' => '2025-11-10'],

            // SCHOLARSHIPS
            ['category' => 'scholarships', 'name' => 'NSP Post Matric OBC 2025', 'hindi_name' => 'एनएसपी पोस्ट मेट्रिक ओबीसी',
             'slug' => 'nsp-obc-2025', 'conducting_body' => 'Ministry of Social Justice', 'post_name' => 'Scholarship',
             'level' => 'central', 'description' => 'Post Matric Scholarship for OBC students studying 11th onwards.',
             'eligibility_rules_json' => ['min_age' => 14, 'caste_category' => ['obc'], 'max_income' => 100000],
             'documents_required_json' => ['Aadhaar', 'Caste Certificate', 'Income Certificate', 'Marksheet'],
             'vacancy_count' => null, 'salary_range' => '₹5,000 – ₹12,000/year',
             'apply_url' => 'https://scholarships.gov.in', 'official_site' => 'https://scholarships.gov.in',
             'apply_end' => '2025-11-30', 'is_featured' => true],

            ['category' => 'scholarships', 'name' => 'PM Research Fellowship 2025', 'hindi_name' => 'पीएम रिसर्च फेलोशिप',
             'slug' => 'pmrf-2025', 'conducting_body' => 'Ministry of Education', 'post_name' => 'Fellowship',
             'level' => 'central', 'description' => 'PM Research Fellowship for PhD students in IITs and IISc.',
             'eligibility_rules_json' => ['min_age' => 22, 'min_education' => 'post graduate'],
             'documents_required_json' => ['Aadhaar', 'B.Tech/M.Tech Certificate', 'Research Proposal'],
             'vacancy_count' => 3000, 'salary_range' => '₹70,000 – ₹80,000/month',
             'apply_url' => 'https://pmrf.in', 'official_site' => 'https://pmrf.in',
             'apply_end' => '2025-12-15'],
               // DISTRICT LEVEL
['category' => 'state-govt', 'name' => 'District Collector Office Recruitment 2025',
 'hindi_name' => 'जिला कलेक्टर कार्यालय भर्ती 2025',
 'slug' => 'district-collector-2025', 'conducting_body' => 'District Administration',
 'post_name' => 'Clerk / Data Entry Operator', 'level' => 'state', 'state_code' => 'BR',
 'district' => 'Patna',
 'description' => 'District level recruitment for clerical and data entry posts in Patna District Collectorate.',
 'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 35, 'min_education' => '12th'],
 'documents_required_json' => ['Aadhaar', '12th Certificate', 'Domicile Certificate', 'Photo'],
 'vacancy_count' => 45, 'salary_range' => '₹18,000 – ₹25,000/month',
 'apply_url' => 'https://patna.nic.in', 'official_site' => 'https://patna.nic.in',
 'apply_end' => '2025-10-30'],

['category' => 'state-govt', 'name' => 'Varanasi District Court Recruitment 2025',
 'hindi_name' => 'वाराणसी जिला न्यायालय भर्ती 2025',
 'slug' => 'varanasi-court-2025', 'conducting_body' => 'District Court Varanasi',
 'post_name' => 'Stenographer / Peon', 'level' => 'state', 'state_code' => 'UP',
 'district' => 'Varanasi',
 'description' => 'District Court Varanasi recruitment for Stenographer and support staff posts.',
 'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 40, 'min_education' => '10th'],
 'documents_required_json' => ['Aadhaar', '10th Certificate', 'Domicile Certificate', 'Photo'],
 'vacancy_count' => 28, 'salary_range' => '₹15,000 – ₹22,000/month',
 'apply_url' => 'https://districts.ecourts.gov.in', 'official_site' => 'https://districts.ecourts.gov.in',
 'apply_end' => '2025-11-15'],

// LOCAL LEVEL
['category' => 'state-govt', 'name' => 'Gram Panchayat Sachiv Recruitment Bihar 2025',
 'hindi_name' => 'ग्राम पंचायत सचिव भर्ती बिहार 2025',
 'slug' => 'gp-sachiv-bihar-2025', 'conducting_body' => 'Bihar Panchayati Raj Department',
 'post_name' => 'Gram Panchayat Sachiv', 'level' => 'state', 'state_code' => 'BR',
 'local_level' => 'gram_panchayat',
 'description' => 'Bihar Gram Panchayat Sachiv recruitment for managing village panchayat administration.',
 'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 37, 'min_education' => '12th'],
 'documents_required_json' => ['Aadhaar', '12th Certificate', 'Domicile Certificate', 'Caste Certificate', 'Photo'],
 'vacancy_count' => 8386, 'salary_range' => '₹12,000 – ₹18,000/month',
 'apply_url' => 'https://state.bihar.gov.in/panchayatiraj', 'official_site' => 'https://state.bihar.gov.in/panchayatiraj',
 'apply_end' => '2025-09-30', 'is_featured' => true],

['category' => 'state-govt', 'name' => 'Municipality Health Worker Recruitment UP 2025',
 'hindi_name' => 'नगर पालिका स्वास्थ्य कार्यकर्ता भर्ती 2025',
 'slug' => 'municipality-health-up-2025', 'conducting_body' => 'UP Nagar Palika Parishad',
 'post_name' => 'Health Worker / Safai Karmachari', 'level' => 'state', 'state_code' => 'UP',
 'local_level' => 'municipality',
 'description' => 'UP Municipality recruitment for health workers and sanitation staff.',
 'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 40, 'min_education' => '8th'],
 'documents_required_json' => ['Aadhaar', 'Education Certificate', 'Domicile Certificate', 'Photo'],
 'vacancy_count' => 1250, 'salary_range' => '₹10,000 – ₹15,000/month',
 'apply_url' => 'https://upnagarpanchayat.org', 'official_site' => 'https://upnagarpanchayat.org',
 'apply_end' => '2025-10-20'],

['category' => 'state-govt', 'name' => 'Block Development Office Recruitment 2025',
 'hindi_name' => 'प्रखंड विकास कार्यालय भर्ती 2025',
 'slug' => 'bdo-recruitment-2025', 'conducting_body' => 'Block Development Office',
 'post_name' => 'Block Level Officer / Assistant', 'level' => 'state', 'state_code' => 'BR',
 'local_level' => 'block',
 'description' => 'Block level recruitment for development officers and assistants across Bihar blocks.',
 'eligibility_rules_json' => ['min_age' => 21, 'max_age' => 37, 'min_education' => 'graduate'],
 'documents_required_json' => ['Aadhaar', 'Graduation Certificate', 'Domicile Certificate', 'Photo'],
 'vacancy_count' => 534, 'salary_range' => '₹20,000 – ₹35,000/month',
 'apply_url' => 'https://state.bihar.gov.in', 'official_site' => 'https://state.bihar.gov.in',
 'apply_end' => '2025-11-01'],

['category' => 'state-govt', 'name' => 'Municipal Corporation Teacher Recruitment 2025',
 'hindi_name' => 'नगर निगम शिक्षक भर्ती 2025',
 'slug' => 'municipal-corp-teacher-2025', 'conducting_body' => 'Municipal Corporation',
 'post_name' => 'Primary Teacher', 'level' => 'state', 'state_code' => 'MH',
 'local_level' => 'corporation',
 'description' => 'Mumbai Municipal Corporation recruitment for primary school teachers.',
 'eligibility_rules_json' => ['min_age' => 21, 'max_age' => 38, 'min_education' => 'graduate'],
 'documents_required_json' => ['Aadhaar', 'B.Ed Certificate', 'Graduation Certificate', 'Photo'],
 'vacancy_count' => 2407, 'salary_range' => '₹28,900 – ₹62,200/month',
 'apply_url' => 'https://mcgm.gov.in', 'official_site' => 'https://mcgm.gov.in',
 'apply_end' => '2025-10-25'],

['category' => 'state-govt', 'name' => 'Tehsil Office Lekhpal Recruitment UP 2025',
 'hindi_name' => 'तहसील लेखपाल भर्ती उत्तर प्रदेश 2025',
 'slug' => 'lekhpal-up-2025', 'conducting_body' => 'UP Revenue Board',
 'post_name' => 'Lekhpal', 'level' => 'state', 'state_code' => 'UP',
 'local_level' => 'tehsil',
 'description' => 'UP Lekhpal recruitment for revenue record keeping at tehsil level across Uttar Pradesh.',
 'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 40, 'min_education' => '12th'],
 'documents_required_json' => ['Aadhaar', '12th Certificate', 'Domicile Certificate', 'Photo'],
 'vacancy_count' => 3638, 'salary_range' => '₹20,000 – ₹30,000/month',
 'apply_url' => 'https://upsssc.gov.in', 'official_site' => 'https://upsssc.gov.in',
 'apply_end' => '2025-09-20', 'is_featured' => true],

             
        ];

        foreach ($opportunities as $data) {
            $category = OpportunityCategory::where('slug', $data['category'])->first();
            if (!$category) continue;

            Opportunity::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'category_id'             => $category->id,
                    'name'                    => $data['name'],
                    'hindi_name'              => $data['hindi_name'],
                    'slug'                    => $data['slug'],
                    'conducting_body'         => $data['conducting_body'],
                    'post_name'               => $data['post_name'],
                    'level'                   => $data['level'],
                    'state_code'              => $data['state_code'] ?? null,
                    'description'             => $data['description'],
                    'eligibility_rules_json'  => $data['eligibility_rules_json'],
                    'physical_standards_json' => $data['physical_standards_json'] ?? null,
                    'documents_required_json' => $data['documents_required_json'],
                    'vacancy_count'           => $data['vacancy_count'] ?? null,
                    'salary_range'            => $data['salary_range'] ?? null,
                    'apply_url'               => $data['apply_url'] ?? null,
                    'official_site'           => $data['official_site'] ?? null,
                    'apply_end'               => $data['apply_end'] ?? null,
                    'is_active'               => true,
                    'is_featured'             => $data['is_featured'] ?? false,
                ]
            );
        }

        $this->command->info('✅ ' . count($opportunities) . ' opportunities seeded!');
    }
}