<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Scheme;
use App\Models\SchemeCategory;

class SchemeSeeder extends Seeder
{
    public function run(): void
    {
        $schemes = [

            // ── FINANCIAL ──────────────────────────────────────
            [
                'category' => 'financial',
                'name' => 'PM Jan Dhan Yojana',
                'hindi_name' => 'प्रधानमंत्री जन धन योजना',
                'slug' => 'pm-jan-dhan-yojana',
                'ministry' => 'Ministry of Finance',
                'description' => 'Zero balance bank account with RuPay debit card, accident insurance of Rs.2 lakh and overdraft facility.',
                'benefit_value' => 200000,
                'benefit_type' => 'insurance',
                'eligibility_rules_json' => ['min_age' => 10, 'requires_bank_account' => false],
                'portal_url' => 'https://pmjdy.gov.in',
                'helpline' => '1800-11-0001',
                'is_central' => true,
            ],
            [
                'category' => 'financial',
                'name' => 'PM Jeevan Jyoti Bima Yojana',
                'hindi_name' => 'प्रधानमंत्री जीवन ज्योति बीमा योजना',
                'slug' => 'pmjjby',
                'ministry' => 'Ministry of Finance',
                'description' => 'Life insurance cover of Rs.2 lakh at just Rs.436/year for ages 18-50.',
                'benefit_value' => 200000,
                'benefit_type' => 'insurance',
                'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 50],
                'portal_url' => 'https://jansuraksha.gov.in',
                'helpline' => '1800-180-1111',
                'is_central' => true,
            ],
            [
                'category' => 'financial',
                'name' => 'PM Suraksha Bima Yojana',
                'hindi_name' => 'प्रधानमंत्री सुरक्षा बीमा योजना',
                'slug' => 'pmsby',
                'ministry' => 'Ministry of Finance',
                'description' => 'Accident insurance of Rs.2 lakh at just Rs.20/year for ages 18-70.',
                'benefit_value' => 200000,
                'benefit_type' => 'insurance',
                'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 70],
                'portal_url' => 'https://jansuraksha.gov.in',
                'helpline' => '1800-180-1111',
                'is_central' => true,
            ],
            [
                'category' => 'financial',
                'name' => 'Atal Pension Yojana',
                'hindi_name' => 'अटल पेंशन योजना',
                'slug' => 'atal-pension-yojana',
                'ministry' => 'Ministry of Finance',
                'description' => 'Guaranteed pension of Rs.1000-5000/month after age 60 for unorganised sector workers.',
                'benefit_value' => 60000,
                'benefit_type' => 'pension',
                'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 40, 'occupation' => 'unorganised'],
                'portal_url' => 'https://npscra.nsdl.co.in',
                'helpline' => '1800-110-708',
                'is_central' => true,
            ],
            [
                'category' => 'financial',
                'name' => 'LPG Ujjwala Yojana',
                'hindi_name' => 'उज्ज्वला योजना',
                'slug' => 'ujjwala-yojana',
                'ministry' => 'Ministry of Petroleum',
                'description' => 'Free LPG connection with first refill free for BPL families.',
                'benefit_value' => 1600,
                'benefit_type' => 'subsidy',
                'eligibility_rules_json' => ['bpl_status' => true, 'gender' => 'female'],
                'portal_url' => 'https://pmuy.gov.in',
                'helpline' => '1906',
                'is_central' => true,
            ],

            // ── HEALTH ─────────────────────────────────────────
            [
                'category' => 'health',
                'name' => 'Ayushman Bharat PM-JAY',
                'hindi_name' => 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना',
                'slug' => 'ayushman-bharat',
                'ministry' => 'Ministry of Health',
                'description' => 'Health insurance cover of Rs.5 lakh per family per year for secondary and tertiary hospitalization.',
                'benefit_value' => 500000,
                'benefit_type' => 'insurance',
                'eligibility_rules_json' => ['bpl_status' => true, 'max_income' => 100000],
                'portal_url' => 'https://pmjay.gov.in',
                'helpline' => '14555',
                'is_central' => true,
            ],
            [
                'category' => 'health',
                'name' => 'Janani Suraksha Yojana',
                'hindi_name' => 'जननी सुरक्षा योजना',
                'slug' => 'janani-suraksha-yojana',
                'ministry' => 'Ministry of Health',
                'description' => 'Cash assistance of Rs.1400 (rural) and Rs.1000 (urban) to pregnant women for institutional delivery.',
                'benefit_value' => 1400,
                'benefit_type' => 'cash',
                'eligibility_rules_json' => ['gender' => 'female', 'bpl_status' => true],
                'portal_url' => 'https://nhm.gov.in/index1.php?lang=1&level=3&sublinkid=841&lid=309',
                'helpline' => '104',
                'is_central' => true,
            ],
            [
                'category' => 'health',
                'name' => 'PM Jan Aushadhi Scheme',
                'hindi_name' => 'प्रधानमंत्री जन औषधि योजना',
                'slug' => 'jan-aushadhi',
                'ministry' => 'Ministry of Chemicals',
                'description' => 'Generic medicines at 50-90% lower price than branded medicines at Jan Aushadhi Kendras.',
                'benefit_value' => 5000,
                'benefit_type' => 'discount',
                'eligibility_rules_json' => [],
                'portal_url' => 'https://janaushadhi.gov.in',
                'helpline' => '1800-111-255',
                'is_central' => true,
            ],

            // ── EDUCATION ──────────────────────────────────────
            [
                'category' => 'education',
                'name' => 'National Scholarship Portal',
                'hindi_name' => 'राष्ट्रीय छात्रवृत्ति पोर्टल',
                'slug' => 'national-scholarship-portal',
                'ministry' => 'Ministry of Education',
                'description' => 'Central scholarships for SC/ST/OBC/Minority students from class 1 to PhD level.',
                'benefit_value' => 25000,
                'benefit_type' => 'scholarship',
                'eligibility_rules_json' => ['max_income' => 250000, 'caste_category' => ['sc','st','obc']],
                'portal_url' => 'https://scholarships.gov.in',
                'helpline' => '0120-6619540',
                'is_central' => true,
            ],
            [
                'category' => 'education',
                'name' => 'Vidya Lakshmi Education Loan',
                'hindi_name' => 'विद्या लक्ष्मी शिक्षा ऋण',
                'slug' => 'vidya-lakshmi',
                'ministry' => 'Ministry of Education',
                'description' => 'Single window for education loan applications to multiple banks. Loans up to Rs.6.5 lakh without collateral.',
                'benefit_value' => 650000,
                'benefit_type' => 'loan',
                'eligibility_rules_json' => ['min_age' => 18, 'max_age' => 35],
                'portal_url' => 'https://www.vidyalakshmi.co.in',
                'helpline' => '1800-572-8888',
                'is_central' => true,
            ],
            [
                'category' => 'education',
                'name' => 'PM YASASVI Scholarship',
                'hindi_name' => 'पीएम यशस्वी छात्रवृत्ति',
                'slug' => 'pm-yasasvi',
                'ministry' => 'Ministry of Social Justice',
                'description' => 'Scholarship for OBC, EBC and DNT students studying in class 9-12. Up to Rs.75,000/year.',
                'benefit_value' => 75000,
                'benefit_type' => 'scholarship',
                'eligibility_rules_json' => ['caste_category' => ['obc'], 'max_income' => 250000],
                'portal_url' => 'https://yet.nta.ac.in',
                'helpline' => '011-40759000',
                'is_central' => true,
            ],

            // ── HOUSING ────────────────────────────────────────
            [
                'category' => 'housing',
                'name' => 'PM Awas Yojana Gramin',
                'hindi_name' => 'प्रधानमंत्री आवास योजना ग्रामीण',
                'slug' => 'pmay-gramin',
                'ministry' => 'Ministry of Rural Development',
                'description' => 'Financial assistance of Rs.1.2 lakh (plain) and Rs.1.3 lakh (hilly) for construction of pucca house.',
                'benefit_value' => 130000,
                'benefit_type' => 'grant',
                'eligibility_rules_json' => ['bpl_status' => true, 'house_type' => 'kutcha'],
                'portal_url' => 'https://pmayg.nic.in',
                'helpline' => '1800-11-6446',
                'is_central' => true,
            ],
            [
                'category' => 'housing',
                'name' => 'PM Awas Yojana Urban',
                'hindi_name' => 'प्रधानमंत्री आवास योजना शहरी',
                'slug' => 'pmay-urban',
                'ministry' => 'Ministry of Housing',
                'description' => 'Interest subsidy of up to Rs.2.67 lakh on home loans for EWS/LIG/MIG categories.',
                'benefit_value' => 267000,
                'benefit_type' => 'subsidy',
                'eligibility_rules_json' => ['max_income' => 1800000],
                'portal_url' => 'https://pmaymis.gov.in',
                'helpline' => '1800-11-3377',
                'is_central' => true,
            ],

            // ── AGRICULTURE ────────────────────────────────────
            [
                'category' => 'agriculture',
                'name' => 'PM KISAN Samman Nidhi',
                'hindi_name' => 'प्रधानमंत्री किसान सम्मान निधि',
                'slug' => 'pm-kisan',
                'ministry' => 'Ministry of Agriculture',
                'description' => 'Direct income support of Rs.6000/year in 3 installments of Rs.2000 to farmer families.',
                'benefit_value' => 6000,
                'benefit_type' => 'cash',
                'eligibility_rules_json' => ['occupation' => 'farmer', 'land_acres' => ['min' => 0.01]],
                'portal_url' => 'https://pmkisan.gov.in',
                'helpline' => '155261',
                'is_central' => true,
            ],
            [
                'category' => 'agriculture',
                'name' => 'PM Fasal Bima Yojana',
                'hindi_name' => 'प्रधानमंत्री फसल बीमा योजना',
                'slug' => 'pmfby',
                'ministry' => 'Ministry of Agriculture',
                'description' => 'Crop insurance at very low premium — 2% for Kharif, 1.5% for Rabi crops.',
                'benefit_value' => 50000,
                'benefit_type' => 'insurance',
                'eligibility_rules_json' => ['occupation' => 'farmer'],
                'portal_url' => 'https://pmfby.gov.in',
                'helpline' => '1800-200-7710',
                'is_central' => true,
            ],
            [
                'category' => 'agriculture',
                'name' => 'Kisan Credit Card',
                'hindi_name' => 'किसान क्रेडिट कार्ड',
                'slug' => 'kisan-credit-card',
                'ministry' => 'Ministry of Agriculture',
                'description' => 'Short term credit up to Rs.3 lakh at 4% interest rate for farmers for crop production.',
                'benefit_value' => 300000,
                'benefit_type' => 'loan',
                'eligibility_rules_json' => ['occupation' => 'farmer'],
                'portal_url' => 'https://www.nabard.org/content.aspx?id=572',
                'helpline' => '1800-180-1551',
                'is_central' => true,
            ],
            [
                'category' => 'agriculture',
                'name' => 'Soil Health Card Scheme',
                'hindi_name' => 'मृदा स्वास्थ्य कार्ड योजना',
                'slug' => 'soil-health-card',
                'ministry' => 'Ministry of Agriculture',
                'description' => 'Free soil health card with nutrient status and fertilizer recommendations every 2 years.',
                'benefit_value' => 500,
                'benefit_type' => 'service',
                'eligibility_rules_json' => ['occupation' => 'farmer'],
                'portal_url' => 'https://soilhealth.dac.gov.in',
                'helpline' => '1800-180-1551',
                'is_central' => true,
            ],

            // ── EMPLOYMENT ─────────────────────────────────────
            [
                'category' => 'employment',
                'name' => 'MGNREGA',
                'hindi_name' => 'महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी',
                'slug' => 'mgnrega',
                'ministry' => 'Ministry of Rural Development',
                'description' => 'Guaranteed 100 days of wage employment per year to rural households. Wage Rs.220-350/day.',
                'benefit_value' => 35000,
                'benefit_type' => 'employment',
                'eligibility_rules_json' => ['state' => 'rural'],
                'portal_url' => 'https://nrega.nic.in',
                'helpline' => '1800-111-555',
                'is_central' => true,
            ],
            [
                'category' => 'employment',
                'name' => 'PM Kaushal Vikas Yojana',
                'hindi_name' => 'प्रधानमंत्री कौशल विकास योजना',
                'slug' => 'pmkvy',
                'ministry' => 'Ministry of Skill Development',
                'description' => 'Free skill training with Rs.8000 reward on certification for youth aged 15-45.',
                'benefit_value' => 8000,
                'benefit_type' => 'training',
                'eligibility_rules_json' => ['min_age' => 15, 'max_age' => 45],
                'portal_url' => 'https://www.pmkvyofficial.org',
                'helpline' => '1800-123-9626',
                'is_central' => true,
            ],
            [
                'category' => 'employment',
                'name' => 'PM Rozgar Protsahan Yojana',
                'hindi_name' => 'प्रधानमंत्री रोजगार प्रोत्साहन योजना',
                'slug' => 'pmrpy',
                'ministry' => 'Ministry of Labour',
                'description' => 'Government pays 12% EPF contribution for new employees earning up to Rs.15000/month.',
                'benefit_value' => 21600,
                'benefit_type' => 'subsidy',
                'eligibility_rules_json' => ['max_income' => 180000],
                'portal_url' => 'https://pmrpy.gov.in',
                'helpline' => '1800-11-9090',
                'is_central' => true,
            ],

            // ── WOMEN & CHILD ───────────────────────────────────
            [
                'category' => 'women',
                'name' => 'PM Matru Vandana Yojana',
                'hindi_name' => 'प्रधानमंत्री मातृ वंदना योजना',
                'slug' => 'pmmvy',
                'ministry' => 'Ministry of Women & Child',
                'description' => 'Cash incentive of Rs.5000 in instalments to pregnant and lactating mothers for first live birth.',
                'benefit_value' => 5000,
                'benefit_type' => 'cash',
                'eligibility_rules_json' => ['gender' => 'female'],
                'portal_url' => 'https://pmmvy.wcd.gov.in',
                'helpline' => '7998799804',
                'is_central' => true,
            ],
            [
                'category' => 'women',
                'name' => 'Sukanya Samriddhi Yojana',
                'hindi_name' => 'सुकन्या समृद्धि योजना',
                'slug' => 'sukanya-samriddhi',
                'ministry' => 'Ministry of Finance',
                'description' => 'High interest savings scheme for girl child at 8.2% p.a. Tax free maturity amount.',
                'benefit_value' => 1500000,
                'benefit_type' => 'savings',
                'eligibility_rules_json' => ['gender' => 'female', 'max_age' => 10],
                'portal_url' => 'https://www.indiapost.gov.in/Financial/pages/content/sukanya.aspx',
                'helpline' => '1800-266-6868',
                'is_central' => true,
            ],
            [
                'category' => 'women',
                'name' => 'Beti Bachao Beti Padhao',
                'hindi_name' => 'बेटी बचाओ बेटी पढ़ाओ',
                'slug' => 'bbbp',
                'ministry' => 'Ministry of Women & Child',
                'description' => 'Scheme to address declining child sex ratio and promote education of girl child.',
                'benefit_value' => 0,
                'benefit_type' => 'awareness',
                'eligibility_rules_json' => ['gender' => 'female'],
                'portal_url' => 'https://wcd.nic.in/bbbp-schemes',
                'helpline' => '011-23388612',
                'is_central' => true,
            ],

            // ── ELDERLY & DISABLED ──────────────────────────────
            [
                'category' => 'elderly',
                'name' => 'Indira Gandhi National Old Age Pension',
                'hindi_name' => 'इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन',
                'slug' => 'ignoaps',
                'ministry' => 'Ministry of Rural Development',
                'description' => 'Monthly pension of Rs.200-500 for BPL citizens aged 60 and above.',
                'benefit_value' => 6000,
                'benefit_type' => 'pension',
                'eligibility_rules_json' => ['min_age' => 60, 'bpl_status' => true],
                'portal_url' => 'https://nsap.nic.in',
                'helpline' => '1800-111-555',
                'is_central' => true,
            ],
            [
                'category' => 'elderly',
                'name' => 'ADIP Scheme for Disabled',
                'hindi_name' => 'दिव्यांगजन सहायता योजना',
                'slug' => 'adip-scheme',
                'ministry' => 'Ministry of Social Justice',
                'description' => 'Free assistive devices like wheelchair, hearing aid, artificial limbs for disabled persons.',
                'benefit_value' => 20000,
                'benefit_type' => 'goods',
                'eligibility_rules_json' => ['disability' => true, 'max_income' => 200000],
                'portal_url' => 'https://alimco.in/adip.aspx',
                'helpline' => '1800-180-5129',
                'is_central' => true,
            ],

            // ── DOCUMENTS ──────────────────────────────────────
            [
                'category' => 'documents',
                'name' => 'Aadhaar Enrollment',
                'hindi_name' => 'आधार नामांकन',
                'slug' => 'aadhaar',
                'ministry' => 'UIDAI',
                'description' => 'Free Aadhaar card — biometric identity document accepted everywhere in India.',
                'benefit_value' => 0,
                'benefit_type' => 'document',
                'eligibility_rules_json' => [],
                'portal_url' => 'https://uidai.gov.in',
                'helpline' => '1947',
                'is_central' => true,
            ],
            [
                'category' => 'documents',
                'name' => 'Voter ID Card',
                'hindi_name' => 'मतदाता पहचान पत्र',
                'slug' => 'voter-id',
                'ministry' => 'Election Commission of India',
                'description' => 'Free voter identity card for all Indian citizens aged 18 and above.',
                'benefit_value' => 0,
                'benefit_type' => 'document',
                'eligibility_rules_json' => ['min_age' => 18],
                'portal_url' => 'https://voterportal.eci.gov.in',
                'helpline' => '1950',
                'is_central' => true,
            ],
            [
                'category' => 'documents',
                'name' => 'DigiLocker',
                'hindi_name' => 'डिजिलॉकर',
                'slug' => 'digilocker',
                'ministry' => 'MeitY',
                'description' => 'Free digital document wallet — store and share Aadhaar, driving licence, marksheets digitally.',
                'benefit_value' => 0,
                'benefit_type' => 'service',
                'eligibility_rules_json' => [],
                'portal_url' => 'https://digilocker.gov.in',
                'helpline' => '1800-3000-3468',
                'is_central' => true,
            ],

            // ── BUSINESS ───────────────────────────────────────
            [
                'category' => 'business',
                'name' => 'PM MUDRA Yojana',
                'hindi_name' => 'प्रधानमंत्री मुद्रा योजना',
                'slug' => 'mudra-yojana',
                'ministry' => 'Ministry of Finance',
                'description' => 'Collateral free loans up to Rs.10 lakh for non-farm small businesses. Shishu/Kishor/Tarun categories.',
                'benefit_value' => 1000000,
                'benefit_type' => 'loan',
                'eligibility_rules_json' => ['occupation' => 'business'],
                'portal_url' => 'https://mudra.org.in',
                'helpline' => '1800-180-1111',
                'is_central' => true,
            ],
            [
                'category' => 'business',
                'name' => 'Startup India',
                'hindi_name' => 'स्टार्टअप इंडिया',
                'slug' => 'startup-india',
                'ministry' => 'DPIIT',
                'description' => 'Tax exemptions, funding support, fast track patent filing for DPIIT recognised startups.',
                'benefit_value' => 500000,
                'benefit_type' => 'mixed',
                'eligibility_rules_json' => ['occupation' => 'business', 'min_age' => 18],
                'portal_url' => 'https://startupindia.gov.in',
                'helpline' => '1800-115-565',
                'is_central' => true,
            ],
            [
                'category' => 'business',
                'name' => 'Udyam Registration',
                'hindi_name' => 'उद्यम पंजीकरण',
                'slug' => 'udyam',
                'ministry' => 'Ministry of MSME',
                'description' => 'Free MSME registration giving access to priority lending, government tenders and subsidies.',
                'benefit_value' => 0,
                'benefit_type' => 'registration',
                'eligibility_rules_json' => ['occupation' => 'business'],
                'portal_url' => 'https://udyamregistration.gov.in',
                'helpline' => '1800-111-955',
                'is_central' => true,
            ],

            // ── LEGAL ──────────────────────────────────────────
            [
                'category' => 'legal',
                'name' => 'NALSA Free Legal Aid',
                'hindi_name' => 'नालसा मुफ्त कानूनी सहायता',
                'slug' => 'nalsa',
                'ministry' => 'Ministry of Law & Justice',
                'description' => 'Free legal services including court representation for SC/ST/women/children/disabled/BPL citizens.',
                'benefit_value' => 50000,
                'benefit_type' => 'service',
                'eligibility_rules_json' => ['bpl_status' => true],
                'portal_url' => 'https://nalsa.gov.in',
                'helpline' => '15100',
                'is_central' => true,
            ],
            [
                'category' => 'legal',
                'name' => 'RTI Act',
                'hindi_name' => 'सूचना का अधिकार',
                'slug' => 'rti',
                'ministry' => 'Ministry of Personnel',
                'description' => 'File RTI applications online to get information from any government department within 30 days.',
                'benefit_value' => 0,
                'benefit_type' => 'right',
                'eligibility_rules_json' => [],
                'portal_url' => 'https://rtionline.gov.in',
                'helpline' => '011-24624302',
                'is_central' => true,
            ],

            // ── DIGITAL ────────────────────────────────────────
            [
                'category' => 'digital',
                'name' => 'Common Service Centres',
                'hindi_name' => 'सामान्य सेवा केंद्र',
                'slug' => 'csc',
                'ministry' => 'MeitY',
                'description' => 'Access 300+ government services at your nearest CSC — Aadhaar, PAN, certificates, insurance.',
                'benefit_value' => 0,
                'benefit_type' => 'service',
                'eligibility_rules_json' => [],
                'portal_url' => 'https://csc.gov.in',
                'helpline' => '1800-121-3468',
                'is_central' => true,
            ],
        ];

        foreach ($schemes as $data) {
            $category = SchemeCategory::where('slug', $data['category'])->first();
            if (!$category) continue;

            Scheme::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'category_id'             => $category->id,
                    'name'                    => $data['name'],
                    'hindi_name'              => $data['hindi_name'],
                    'slug'                    => $data['slug'],
                    'ministry'                => $data['ministry'],
                    'description'             => $data['description'],
                    'benefit_value'           => $data['benefit_value'],
                    'benefit_type'            => $data['benefit_type'],
                    'eligibility_rules_json'  => $data['eligibility_rules_json'],
                    'portal_url'              => $data['portal_url'],
                    'helpline'                => $data['helpline'] ?? null,
                    'is_central'              => $data['is_central'],
                    'is_active'               => true,
                    'state'                   => 'central',
                ]
            );
        }

        $this->command->info('✅ ' . count($schemes) . ' schemes seeded!');
    }
}